<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Action
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="primary">
    <button type="button" title="<?= $escaper->escapeHtmlAttr($block->getNextButtonLabel()) ?>" class="action next primary">
        <span><?= $block->escapeHtml($block->getNextButtonLabel()) ?></span>
    </button>
</div>
