<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Action\Previous
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="primary">
    <button type="button" title="<?= $escaper->escapeHtmlAttr($block->getButtonLabel()) ?>" class="action previous primary">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
