<?php
/*
 * Copyright (c) 2011-2023 PFP Łukasz Maksimowicz
 * https://www.ipfp.pl
 * +48 790 790 543
 *
 * Need help or want to customize anything?
 * Drop us a line at our contact page: https://www.ipfp.pl/contact
 *
 * All title, including but not limited to copyrights, in and to the software product
 * and any copies thereof are owned by PFP Łukasz Maksimowicz.
 * All rights not expressly granted are reserved by PFP Łukasz Maksimowicz.
 *
 * @category Module
 * @package SubscriptionProduct
 * @author Łukasz Maksimowicz <maxim@ipfp.pl>
 * @license https://www.ipfp.pl/licenses/magento
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\View\Element\Template $block */

$message = '<span class="pending-form">' . __('Ordered product <span class="item-name">%s</span> requires filling <span class="form-name">%s</span> form. Click <a href="%s">here</a> to complete.') . '</span>';
?>

<?= $escaper->escapeHtml(
    sprintf(
        $message,
        $block->getData('product_name'),
        $block->getData('form_title'),
        $block->getData('form_url')
    ), ['a', 'span']); ?>
