<?php
    /** @var \Magento\Framework\View\Element\Template $block */

    /** @var \Alekseon\WidgetForms\Helper\Data $dataHelper */
    $dataHelper = $block->getData('data_helper');
    $_items = $dataHelper->getCustomerRecords(true);
?>

<?php if (count($_items)) : ?>
    <table>
        <thead>
            <tr>
                <th><?= __('Order'); ?></th>
                <th><?= __('Form Type'); ?></th>
                <th><?= __('Product'); ?></th>
                <th><?= __('Actions'); ?></th>
            </tr>
        </thead>
    <?php $i = 1; ?>
    <?php foreach($_items as $item) : ?>
        <tr>
            <td><?= $item['order_increment_id'] ? ('#' . $item['order_increment_id']) : '----' ?></td>
            <td style="font-weight: bold; color: #0f5293;"><?= $item['form_title'] ?></td>
            <td><?= $item['product_name'] ? $item['product_name'] : '----' ?></td>
            <td>
                <a href="<?= $dataHelper->getEditUrl($item); ?>">Edit</a>
            </td>
        </tr>
    <?php $i++; ?>
    <?php endforeach; ?>
    </table>
<?php else : ?>
    <?= __('No records found'); ?>
<?php endif; ?>
